version: "3.9"
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    image: researchive-api
    volumes:
      - ./api:/usr/src/api
    ports:
      - "8000:8000"
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile.dev
    image: researchive-web
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/usr/src/web
    ports:
      - "3000:3000"