FROM python:3.9-buster

WORKDIR /usr/src/api

# Install requirements.txt - unfortunately, this means that if the dependencies
# change, the container will need to be reloaded.
COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]